<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "jku_folderselector"
 *
 * Auto generated by Extension Builder 2019-10-22
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'BackendFormSelectAFolder',
    'description' => 'Example extension with backend form to select a single folder. Folder is stored as string (FAL identifier). Typo3 7.6',
    'category' => 'doc',
    'author' => '',
    'author_email' => '',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-7.6.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
